<a href="https://colab.research.google.com/github/vaib140498/phase1-python-oops-apis/blob/main/Setup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
arr1 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print(arr1)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [ ]:
diagarr = np.eye(3)
print(diagarr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
nums = np.arange(0,100,8)
print(nums)

[ 0  8 16 24 32 40 48 56 64 72 80 88 96]


In [ ]:
arr2 = np.linspace(0,20,20)
print(arr2)

[ 0.          1.05263158  2.10526316  3.15789474  4.21052632  5.26315789
  6.31578947  7.36842105  8.42105263  9.47368421 10.52631579 11.57894737
 12.63157895 13.68421053 14.73684211 15.78947368 16.84210526 17.89473684
 18.94736842 20.        ]


In [ ]:
print(arr1[1:,1:])
print(arr1[1:,2:])

[[ 5  6  7]
 [ 8  9 10]]
[[ 6  7]
 [ 9 10]]
